name: taskmanager
description: A time-based task management app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # API Integration
  http: ^1.1.0
  json_annotation: ^4.8.1

  # Notifications
flutter_local_notifications: ^16.3.4

provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # JSON Serialization
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
